# Generated by Django 5.2.11 on 2026-03-05 09:25

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(max_length=100, unique=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product_currency', models.CharField(max_length=3)),
                ('product_url', models.URLField()),
                ('product_image', models.URLField(blank=True)),
                ('product_category', models.CharField(max_length=20)),
                ('product_brand', models.CharField(blank=True, max_length=20)),
                ('product_description', models.TextField(blank=True)),
                ('product_is_available', models.BooleanField(null=True)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('product_updated_at', models.DateTimeField(auto_now=True)),
                ('product_is_active', models.BooleanField(null=True)),
                ('product_embedding', pgvector.django.vector.VectorField(dimensions=384, null=True)),
            ],
        ),
    ]
