# Generated by Django 5.2.11 on 2026-03-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='product_is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='product_url',
            field=models.URLField(max_length=500),
        ),
    ]
