# Generated by Django 5.2.11 on 2026-03-06 06:47

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_productdata_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='product_embedding',
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_source_type', models.CharField(max_length=20)),
                ('embedding_source_text', models.CharField(max_length=255)),
                ('embedding_vector', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('product_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.productdata')),
            ],
        ),
    ]
