name: Remote SSH Login
on: 
  push:
    branches: [master]
          jobs:
            build:
            runs-on: ubuntu-latest
            steps:
              - name: Execute remote  SSH commands using password
                uses: appleboy/ssh-action@v1
                with:
                  user: ${{ secrets.EC2_USER }}
                  host: ${{secrets.EC2_HOST }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: whoami